server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_web_bank?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
